# Generated by Django 4.2.2 on 2023-06-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('flag', models.CharField(blank=True, max_length=2, null=True, verbose_name='标志')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel', verbose_name='点赞文章')),
                ('life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='生活琐事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel', verbose_name='点赞视频')),
            ],
            options={
                'verbose_name': '点赞列表',
                'verbose_name_plural': '点赞列表',
                'db_table': 't_star_uer',
            },
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('flag', models.CharField(blank=True, max_length=2, null=True, verbose_name='标志')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel', verbose_name='收藏文章')),
                ('life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='收藏生活')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel', verbose_name='收藏视频')),
            ],
            options={
                'verbose_name': '收藏列表',
                'verbose_name_plural': '收藏列表',
                'db_table': 't_collection_uer',
            },
        ),
    ]
