# Generated by Django 3.2.15 on 2023-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images2/', verbose_name='用户头像'),
        ),
    ]
