# Generated by Django 3.2.15 on 2023-05-18 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0008_auto_20230518_0911'),
        ('user', '0002_alter_usermodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel', verbose_name='点赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel', verbose_name='点赞视频')),
            ],
            options={
                'verbose_name': '点赞列表',
                'verbose_name_plural': '点赞列表',
                'db_table': 't_star_uer',
            },
        ),
        migrations.CreateModel(
            name='FocusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('focus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_user', to=settings.AUTH_USER_MODEL, verbose_name='被关注用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注列表',
                'verbose_name_plural': '关注列表',
                'db_table': 't_focus_uer',
            },
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel', verbose_name='收藏文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel', verbose_name='收藏视频')),
            ],
            options={
                'verbose_name': '收藏列表',
                'verbose_name_plural': '收藏列表',
                'db_table': 't_collection_uer',
            },
        ),
    ]
