# Generated by Django 3.2.15 on 2023-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_collectionmodel_focusmodel_starmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusmodel',
            name='flag',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='标志'),
        ),
    ]
