# Generated by Django 3.2.15 on 2023-05-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230508_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(default='1', max_length=2, verbose_name='性别'),
        ),
    ]
