# Generated by Django 3.2.15 on 2023-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_focusmodel_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='flag',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='标志'),
        ),
        migrations.AddField(
            model_name='starmodel',
            name='flag',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='标志'),
        ),
    ]
