# Generated by Django 3.2.15 on 2023-05-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0009_auto_20230525_2134'),
        ('user', '0005_auto_20230525_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='收藏生活'),
        ),
        migrations.AddField(
            model_name='starmodel',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='生活琐事'),
        ),
    ]
