# Generated by Django 4.2.2 on 2023-06-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('default_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='首页图片')),
                ('running_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数')),
                ('star_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collection_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 't_article',
                'ordering': ['-is_top', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pieces_info.articlemodel')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.commentmodel', verbose_name='评论的评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 't_comment',
            },
        ),
        migrations.CreateModel(
            name='LifeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('copy', models.CharField(max_length=512, verbose_name='文案')),
                ('default_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='首页图片')),
                ('star_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collection_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('is_friend', models.IntegerField(default=0, verbose_name='是否仅好友可见')),
                ('status', models.CharField(blank=True, max_length=4, null=True, verbose_name='作者状态1.阅读2.创作3.开心4.emo5.发呆')),
                ('running_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='播放次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '生活琐事',
                'verbose_name_plural': '生活琐事',
                'db_table': 't_life',
                'ordering': ['-is_top', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('video', models.FileField(upload_to='', verbose_name='视频内容')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频标题')),
                ('star_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collection_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('duration_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频时长')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('img_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='照片文件')),
                ('running_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='播放次数')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('is_success', models.BooleanField(blank=True, max_length=4, null=True, verbose_name='是否发布成功')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 't_video',
                'ordering': ['-is_top', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态0.已读1.未读')),
                ('type_1', models.CharField(default='1', max_length=4, verbose_name='信息类型1.点赞2.收藏3.评论4.关注5.好友申请6.好友通过7.访问空间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel')),
                ('comment_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_1', to='pieces_info.commentmodel', verbose_name='作品的评论')),
                ('comment_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_2', to='pieces_info.commentmodel', verbose_name='评论的评论')),
                ('life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='生活琐事')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL, verbose_name='发起动作的人')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL, verbose_name='接收消息的人')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel')),
            ],
            options={
                'verbose_name': '通知信息',
                'verbose_name_plural': '通知信息',
                'db_table': 't_message',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片内容')),
                ('image_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片相对路径')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pieces_info.articlemodel', verbose_name='文章')),
                ('life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pieces_info.lifemodel', verbose_name='生活琐事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pieces_info.videomodel', verbose_name='视频')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 't_image',
            },
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pieces_info.lifemodel', verbose_name='生活琐事'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pieces_info.videomodel'),
        ),
    ]
