# Generated by Django 4.2.2 on 2023-06-11 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 11, 7, 26, 20, 80220, tzinfo=datetime.timezone.utc), verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_1',
            field=models.CharField(default='1', max_length=4, verbose_name='信息类型1.点赞2.收藏3.评论4.关注5.好友申请6.好友通过7.拒绝好友8.访问空间'),
        ),
    ]
