# Generated by Django 3.2.15 on 2023-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='static/images2/', verbose_name='图片内容'),
        ),
    ]
