# Generated by Django 3.2.15 on 2023-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='图片相对路径'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片内容'),
        ),
    ]
