# Generated by Django 3.2.15 on 2023-05-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0002_auto_20230513_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='img_path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='照片文件'),
        ),
    ]
