# Generated by Django 3.2.15 on 2023-05-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='duration_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='视频时长'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='img_path',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='照片文件'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='running_count',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='播放次数'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='图片内容'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='', verbose_name='视频内容'),
        ),
    ]
