# Generated by Django 3.2.15 on 2023-05-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0003_alter_videomodel_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片相对路径'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='img_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='照片文件'),
        ),
    ]
