# Generated by Django 3.2.15 on 2023-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0005_auto_20230516_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-is_top', '-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'ordering': ['-is_top', '-id'], 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
    ]
