# Generated by Django 3.2.15 on 2023-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0006_auto_20230516_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='running_count',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True, verbose_name='浏览次数'),
        ),
    ]
