# Generated by Django 3.2.15 on 2023-05-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0007_articlemodel_running_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='collection_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='collection_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量'),
        ),
    ]
