# Generated by Django 3.2.15 on 2023-05-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pieces_info', '0008_auto_20230518_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('copy', models.CharField(max_length=512, verbose_name='文案')),
                ('default_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='首页图片')),
                ('star_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collection_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '生活琐事',
                'verbose_name_plural': '生活琐事',
                'db_table': 't_life',
                'ordering': ['-is_top', '-id'],
            },
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pieces_info.lifemodel', verbose_name='生活琐事'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pieces_info.lifemodel', verbose_name='生活琐事'),
        ),
    ]
