# Generated by Django 3.2.15 on 2023-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0009_auto_20230525_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemodel',
            name='running_count',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True, verbose_name='播放次数'),
        ),
    ]
