# Generated by Django 3.2.15 on 2023-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0010_lifemodel_running_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemodel',
            name='is_friend',
            field=models.IntegerField(default=0, verbose_name='是否仅好友可见'),
        ),
        migrations.AddField(
            model_name='lifemodel',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='作者状态'),
        ),
    ]
