# Generated by Django 3.2.15 on 2023-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0011_auto_20230606_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemodel',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作者状态'),
        ),
    ]
