# Generated by Django 3.2.15 on 2023-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0013_alter_lifemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemodel',
            name='status',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='作者状态1.阅读2.创作3.开心4.emo5.发呆'),
        ),
    ]
