# Generated by Django 4.2.2 on 2023-06-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pieces_info', '0014_alter_lifemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.articlemodel')),
                ('life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.lifemodel', verbose_name='生活琐事')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL, verbose_name='发起动作的人')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL, verbose_name='接收消息的人')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.videomodel')),
            ],
            options={
                'verbose_name': '通知信息',
                'verbose_name_plural': '通知信息',
                'db_table': 't_message',
            },
        ),
    ]
