# Generated by Django 4.2.2 on 2023-06-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_info', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.commentmodel', verbose_name='评论的评论'),
        ),
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces_info.commentmodel'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态0.已读1.未读'),
        ),
    ]
